package com.sureshots.app.constant

const val IS_DEBUG_ON = true // TODO: false on live

const val INTENT_EXTRA_OPEN_AS_EDIT_FORM = "INTENT_EXTRA_OPEN_AS_EDIT_FORM"
const val INTENT_EXTRA_SELECTED_ROW: String = "INTENT_EXTRA_SELECTED_ROW"
// const val INTENT_STARTED_BY_MAIN_ACTIVITY = "started_by_main_activity"
// const val INTENT_KEY_SWIPE_TAB_TO_NEXT_SCREEN = "INTENT_KEY_SWIPE_TAB_TO_NEXT_SCREEN"

const val REQUEST_CODE_PICK_IMAGE_PERMISSION = 10001
const val REQUEST_CODE_CAPTURE_IMAGE_PERMISSION = 10002
// const val REQUEST_CODE_TURN_ON_LOCATION_PERMISSION = 10003

const val REQUEST_CODE_PICK_IMAGE = 10011
const val REQUEST_CODE_CAPTURE_IMAGE = 10012
// const val REQUEST_CODE_GET_LOCATION = 10013



class Constant